In [308]:
import pandas as pd
import datetime
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, InputLayer, Reshape, MaxPooling2D, Flatten, Dropout, BatchNormalization

In [310]:
df=pd.read_csv('kc_house_data.csv')

In [312]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [315]:
df['age']=datetime.datetime.now().year-df['yr_built']

In [317]:
df['bedrooms']=df['bedrooms']**2
df['bathrooms']=df['bathrooms']**2
df['sqft_living']=df['sqft_living']**2

In [319]:
df['zipcode']=df['zipcode'].astype('category')

In [321]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,age
0,7129300520,20141013T000000,221900.0,9,1.0000,1392400,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,70
1,6414100192,20141209T000000,538000.0,9,5.0625,6604900,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,74
2,5631500400,20150225T000000,180000.0,4,1.0000,592900,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,92
3,2487200875,20141209T000000,604000.0,16,9.0000,3841600,5000,1.0,0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,60
4,1954400510,20150218T000000,510000.0,9,4.0000,2822400,8080,1.0,0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,38

In [323]:
x=df.drop(['id','date','lat','long','price'],axis=1)
y=df[['price']]

In [325]:
x.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,sqft_living15,sqft_lot15,age
0,9,1.0000,1392400,5650,1.0,0,0,3,7,1180,0,1955,0,98178,1340,5650,70
1,9,5.0625,6604900,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,1690,7639,74
2,4,1.0000,592900,10000,1.0,0,0,3,6,770,0,1933,0,98028,2720,8062,92
3,16,9.0000,3841600,5000,1.0,0,0,5,7,1050,910,1965,0,98136,1360,5000,60
4,9,4.0000,2822400,8080,1.0,0,0,3,8,1680,0,1987,0,98074,1800,7503,38

In [328]:
from sklearn.model_selection import train_test_split

In [330]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20, random_state=42)

In [332]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)  # Eğitim verisini ölçekle
x_test = scaler.transform(x_test)  # Test verisini ölçekle

In [334]:
model=Sequential()
model.add(Dense(120,activation='relu'))
model.add(Dense(80,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(30,activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(1))
model.compile(loss='mse',optimizer='adam')

In [336]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),batch_size=128,epochs=40)

Epoch 1/40
136/136 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 412880437248.0000 - val_loss: 279601840128.0000
Epoch 2/40
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 137625567232.0000 - val_loss: 74698596352.0000
Epoch 3/40
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 58766397440.0000 - val_loss: 60613681152.0000
Epoch 4/40
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 48463196160.0000 - val_loss: 53519642624.0000
Epoch 5/40
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 43540561920.0000 - val_loss: 50148573184.0000
Epoch 6/40
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 39344308224.0000 - val_loss: 48631205888.0000
Epoch 7/40
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 40833773568.0000 - val_loss: 47628480512.0000
Epoch 8/40
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36920004608.0000 - val_loss: 47013974016.0000
Epoch 9/40
136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 37934133248.0000 - val_loss: 46803542016.0000
Epoch 10/40
 98/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 39539355648.0000

KeyboardInterrupt:

In [274]:
tahmin=model.predict(x_test)

136/136 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [275]:
from sklearn.metrics import r2_score, mean_squared_error

In [276]:
r2_score(y_test,tahmin)

0.4181022047996521

In [277]:
mean_squared_error(y_test,tahmin)**0.5

296596.35666002374